<?php
$standad = Mage::getSingleton('moip/standard');
$api = Mage::getSingleton('moip/api');
$api->setContaMoip($standad->getConfigData('conta_moip'));
$api->setAmbiente($standad->getConfigData('ambiente'));
$pgdireto = $api->hasPagamentoDireto();
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('o2ti_moip/js/formulario.js'); ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('o2ti_moip/css/formulario.css'); ?> "media="all">

<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;margin-left:0px; "> 
<div id="checkouto2ti">
<div id="payment_form_<?php echo $this->getMethodCode() ?>" >           
<?php
$nome =  Mage::getSingleton('customer/session')->getCustomer()->getName();
$telefone =  Mage::getSingleton('customer/session')->getCustomer()->getTelephone();
$cpf =  Mage::getSingleton('customer/session')->getCustomer()->getTaxvat();
$dn =  Mage::getSingleton('customer/session')->getCustomer()->getdob();
$dn = date("d/m/Y", strtotime($dn));
?>
<a href="https://site.moip.com.br/compra-protegida/" target="_blank" style="width:260px; float:left;margin-bottom: 15px;
text-align: center;"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/logomoip.png'); ?>" id="imageseguramoip" border="0"></a>

            <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
<label id="meios">
<input onclick="cartao()" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="CartaoCredito" class="radio payment_method_handle validation-passed"  autocomplete="off">
<img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abacartao.png'); ?>" id="imagemcartao" alt="Cartão de Crédito"  onclick="$(this).parent('label').find('input').click()"  />
</label>
            <?php endif; ?>
            <?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
<label id="meios">
<input onclick="boleto()" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="BoletoBancario" class="radio payment_method_handle validation-passed" autocomplete="off">
<img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/ababoleto.png'); ?>"  id="imageboleto" alt="Boleto Bancário"  onclick="$(this).parent('label').find('input').click()"  /></label>
           <?php endif; ?>
            <?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
<label id="meios"><input onclick="transf()" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="DebitoBancario" class="radio payment_method_handle validation-passed" autocomplete="off"> 
<img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abatransf.png'); ?>"  id="imagemtrans" alt="Transferência Bancária" onclick="$(this).parent('label').find('input').click()" /></label>
            <?php endif; ?> 
            
</div>
<div id="checkout-payment-o2ti"></div>
<div id="moip_o2preencha">Por favor, primeiro preencha o endereço de cobrança!</div>
<?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
        <div id="moip_credito" >
        <div id="formcard" >
        <h3>Cartão de Crédito</h3>
<div id="dadosformcartao">
        <div id="bandeiramoipdiv"> 
		<div id="bandeiramoipa">
			<div id="bandeiramoipaa"><label><input id="bandeiramoip" type="radio" name="payment[credito_instituicao]" onclick="visa()"  value="Visa"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipvisa.png'); ?>" onclick="Visa()"   id="Visa" alt="Visa" border="0"></label></div>
			<div id="bandeiramoipaa"><label ><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="mastercard()"  value="Mastercard"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipmaster.png'); ?>" id="Mastercard" alt="Mastercard" border="0"></label></div>
			<div id="bandeiramoipaa"><label><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]"onclick="americanexpress()"  value="AmericanExpress"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipamerican.png'); ?>"id="AmericanExpress" alt="AmericanExpress" border="0"></label></div>
			<div id="bandeiramoipaa"><label><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="diners()"  value="Diners"> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipdiners.png'); ?>" id="Diners" alt="Diners" border="0"></label></div>
			<div id="bandeiramoipaa"><label><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="hipercard()"  value="Hipercard"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moiphiper.png'); ?>" id="Hipercard" alt="Hipercard" border="0"></label></div> 
		</div>
</div>
<div id="checkout-payment-bandeira"></div>
        <label id="dadoscartao" style="margin-top:15px;">Número:</label>
    <input type="text" name="payment[credito_numero]" id="credito_numero" class="required-entry" autocomplete="off">
<br />
    <label id="dadoscartao">Validade:</label>
    <select name="payment[credito_expiracao_mes]" id="credito_expiracao_mes" class="required-entry" autocomplete="off">
      <option value="">Mês</option>
      <option value="01">01</option>
      <option value="02">02</option>
      <option value="03">03</option>
      <option value="04">04</option>
      <option value="05">05</option>
      <option value="06">06</option>
      <option value="07">07</option>
      <option value="08">08</option>
      <option value="09">09</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
    </select>
    <select name="payment[credito_expiracao_ano]" id="credito_expiracao_ano" class="required-entry" autocomplete="off">
      <option value="">Ano</option>
      <option value="12">12</option>
      <option value="13">13</option>
      <option value="14">14</option>
      <option value="15">15</option>
      <option value="16">16</option>
      <option value="17">17</option>
      <option value="18">18</option>
      <option value="19">19</option>
      <option value="20">20</option>
      <option value="21">21</option>
      <option value="22">22</option>
      <option value="23">23</option>
      <option value="24">24</option>
      <option value="25">25</option>
    </select>
<br />

	<label id="dadoscartao">Código de segurança:</label>
    <input type="text" name="payment[credito_codigo_seguranca]" class="required-entry" style="width: 30px" id="credito_codigo_seguranca" autocomplete="off">
<br />
<?php


$data = $standad->getQuote()->getShippingAddress();
$data->getGrandTotal();

?>
            <?php if ($standad->getConfigData('parcelamento')): ?>
            <label id="dadoscartaoopc">Opções de pagamento:</label>
            <select name="payment[credito_parcelamento]" id="credito_parcelamento" class="required-entry" >
                 <?php
                      $data = $standad->getQuote()->getShippingAddress();
$data = $standad->getQuote()->getShippingAddress();
$data->getGrandTotal();
/*alteracao minha bruno elisei. not! $parcelamento = $api->getParcelamento("<div id=\"updatevalue\">1000<\div>");*/
 
                      $parcelamento = $api->getParcelamento($data->getGrandTotal());
                  foreach ($parcelamento as $k => $v): ?>
                      <option value="<?php echo $k ?>"><?php echo $k . "x R$ ".$v['valor']." | No total de R$ " .$v['total'] ?></option>
                 <?php endforeach; ?>
            </select>
            <?php endif; ?>
            <div id="addparcelas">
                                            <?php
                                            $standard = Mage::getSingleton('moip/standard');
                                                    $parcelamento = $standard->getInfoParcelamento();
                                            if ($parcelamento['juros1'] == 0)
                                            {
                                            echo "</br><div id=\"addparcelasdesc\"> Sem juros até ".$parcelamento['ate1']." parcelas</div>";
                                            if ($parcelamento['ate1'] < 13)
                                            {
                                            echo ", após juros de 1.99 ao mês.";
                                            }
                                            }
                                            if ($parcelamento['juros1'] >= "1.99")
                                            {
                                            echo "</br>Com juros de ".$parcelamento['juros1']." ao mês.";
                                            }
                                            ?>
                                         </div>
        </div>
        </div>
        <div id="alterar">
        <label>
        <input type="radio" border="0" onclick="alterar()" id="alterarin" autocomplete="off">
        Alterar dados do Titular do cartão
        </label>
        </div>
        <div id="manter">
        <label>
        <input type="radio" border="0" onclick="manter()" id="alterarin" autocomplete="off">
        Manter dados do Titular do cartão
        </label>
        </div>
        <div id="formcli">
        <h3>Dados do Titular</h3>
        <label id="dadoscliente">Nome no cartão:</label>
        <input type="text" name="payment[credito_portador_nome]" value="<?php echo $nome; ?>" class="required-entry" id="credito_portador_nome" autocomplete="off">
        <label id="dadoscliente">CPF:</label>
        <input type="text" name="payment[credito_portador_cpf]" class="required-entry validar_cpf" placeholder="Ex. 111.111.111-11" id="credito_portador_cpf" value="<?php echo $cpf; ?>" autocomplete="off">
        <label id="dadoscliente">Telefone:</label>
        <input type="text" name="payment[credito_portador_telefone]" id="credito_portador_telefone" onkeypress="return txtBoxFormat(this, '(99)9999-9999', event);" maxlength="14" value="<?php echo $telefone; ?>" placeholder="Ex. (19)9999-9999" class="required-entry" autocomplete="off">
        <label id="dadoscliente">Data nascimento:</label>
        <input type="text" name="payment[credito_portador_nascimento]" id="credito_portador_nascimento" onkeypress="return txtBoxFormat(this, '99/99/9999', event);" maxlength="10" value="<?php echo $dn ?>" placeholder="Ex. 10/10/1985" class="required-entry" autocomplete="off">
        </div>
        </div>
    <?php endif; ?>
	<?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
        <div id="moip_boleto" >
        <h3>Boleto Bancário</h3>
        <div id="pagboleto">                 
        <?php
        $standard = Mage::getSingleton('moip/standard');
        $parcelamento = $standard->getInfoParcelamento();
        if ($parcelamento['de2'] != 0)
        {
        echo "<div id=\"pagboletodesconto\">Com desconto de  ".$parcelamento['de2']."%</div><br>";
        }
        echo "Pagável em qualquer agência bancária ou casas lotéricas.";
        ?>
        </div>
        </div>
    <?php endif; ?> 
	<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
        <div id="moip_debito">
        <h3>Transferência Bancária</h3>
        <div id="pagdebito">
        Após finalizar o pedido você será redirecionado ao site do seu banco...
        </div>
        <div id="checkout-payment-o2ti-deb">
        Por favor, selecione o banco!
        </div>
        <div id="moip_debito_bandeiras">
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]"  onclick="bb();"  value="BancoDoBrasil" autocomplete="off"> 
        <img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bb.png'); ?>" onclick="$(this).parent('label').find('input').click()"  alt="Banco do Brasil" id="debbb" >
        </label>
        <label onclick="bradesco()">
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="bradesco()" value="Bradesco" autocomplete="off">
        <img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bradesco.png'); ?>" onclick="$(this).parent('label').find('input').click()" id="debbradesco" alt="Bradesco" >
        </label>
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="itau()"  value="Itau" autocomplete="off">
        <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/itau.png'); ?>" onclick="$(this).parent('label').find('input').click()" id="debitau" alt="Itaú"  >
        </label>
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="banrisul()" value="Banrisul"  autocomplete="off">
        <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/banrisul.png'); ?>" onclick="$(this).parent('label').find('input').click()" id="Banrisul" alt="Banrisul"  >
        </label>
        </div>
        </div>
<div id="checkout-payment-banco"></div>
    <?php endif; ?>
<a href="https://site.moip.com.br/compra-protegida/" target="_blank"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/logomoipck.png'); ?>" id="imageseguramoip" border="0"></a>
</div>

</ul>