<?php
$standad = Mage::getSingleton('moip/standard');
$api = Mage::getSingleton('moip/api');
$api->setContaMoip($standad->getConfigData('conta_moip'));
$api->setAmbiente($standad->getConfigData('ambiente'));
$pgdireto = $api->hasPagamentoDireto();
?>
<a href="https://www.moip.com.br" target="_blank"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/logomoipck.png');?>" style="margin-top:15px;" border="0"></a>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;margin-left: 10px;margin-top: 25px;float: left;width: 300px;">
           
<?php
$cpf =  Mage::getSingleton('customer/session')->getCustomer()->getTaxvat();
$dn =  Mage::getSingleton('customer/session')->getCustomer()->getdob();
$dn = date("d/m/Y", strtotime($dn));
?>
            <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
                        <label style="float:left;margin-bottom: 25px;"><input type="radio"  alt="Cartão de Crédito"  border="0"  onclick="
 document.getElementById('moip_credito').style.display = 'block';
 document.getElementById('moip_o2preencha').style.display = 'none';
 document.getElementById('moip_boleto').style.display = 'none';
 document.getElementById('moip_debito').style.display = 'none';
if (!document.getElementById('shipping:firstname').value) {
 document.getElementById('credito_portador_nome').value = document.getElementById('billing:firstname').value + ' ' + document.getElementById('billing:lastname').value;
 document.getElementById('credito_portador_telefone').value = document.getElementById('billing:telephone').value;
 document.getElementById('credito_portador_cpf').value = document.getElementById('billing:taxvat').value;
 document.getElementById('credito_portador_nascimento').value = document.getElementById('billing:day').value + '/' + document.getElementById('billing:month').value + '/' + document.getElementById('billing:year').value
} else {
 document.getElementById('credito_portador_nome').value = document.getElementById('shipping:firstname').value + ' ' + document.getElementById('shipping:lastname').value;
 document.getElementById('credito_portador_telefone').value = document.getElementById('shipping:telephone').value;
 document.getElementById('credito_portador_cpf').value = document.getElementById('<?php echo $cpf; ?>').value;
 document.getElementById('credito_portador_nascimento').value = document.getElementById('billing:day').value + '/' + document.getElementById('billing:month').value + '/' + document.getElementById('billing:year').value
}" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="<?php echo Mage::helper('payment')->__("forma_pagamento") ?>" value="CartaoCredito" class="radio payment_method_handle validation-passed" style="display: none;"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abacartao.png'); ?>"  alt="Boleto Bancário"  style="cursor:pointer;margin-botton:25px;"></label>
            <?php endif; ?>
            <?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
                <label style="float:left;margin-bottom: 25px;"> <input onclick="document.getElementById('moip_debito').style.display='none';document.getElementById('moip_o2preencha').style.display='none';document.getElementById('moip_boleto').style.display='block';document.getElementById('moip_credito').style.display='none'" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="<?php echo Mage::helper('payment')->__("forma_pagamento") ?>" value="BoletoBancario" class="radio payment_method_handle validation-passed"  style="display: none;" /> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/ababoleto.png'); ?>"  style="cursor:pointer;margin-botton:25px;" alt="Boleto Bancário" ></label>
           <?php endif; ?>
            <?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
                    <label style="float:left;margin-bottom: 25px;"><input onclick="document.getElementById('moip_debito').style.display='block';document.getElementById('moip_o2preencha').style.display='none';document.getElementById('moip_boleto').style.display='none';document.getElementById('moip_credito').style.display='none'" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="<?php echo Mage::helper('payment')->__("forma_pagamento") ?>" value="DebitoBancario"  class="radio payment_method_handle validation-passed"  style="display: none;" /> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abatransf.png'); ?>"  style="cursor:pointer;margin-botton:25px;" alt="Transferência Bancária" ></label>
            <?php endif; ?> 
            
            
                
                                        
<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
                    <div id="moip_debito" style="display:none;float:left;width:300px;margin-bottom:25px;">
<h3>Transferência Bancária</h3>
                        <ul style="margin-left: 10px;" >
                            <li style="display:block; float: left;"><label><input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" value="BancoDoBrasil" style="display:none;"/> <img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bb.png'); ?>" alt="Banco do Brasil" style="cursor:pointer;"></label></li>
                            <li style="display:block; float: left;"><label><input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" value="Bradesco" style="display:none;"/> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bradesco.png'); ?>"   style="cursor:pointer;" alt="Bradesco"> </label></li>
                            <li style="display:block; float: left;"><label><input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" style="display:none;" value="Itau" /> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/itau.png'); ?>"  alt="Itaú" style="cursor:pointer;" > </label></li>
                            <li style="display:block; float: left;"><label><input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" value="Banrisul" style="display:none;"/> <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/banrisul.png'); ?>"  alt="Banrisul" style="cursor:pointer;">
</label></li>
                        </ul>
<div id="checkout-payment-o2ti-deb"><div class="validation-advice" id="advice-required-entry_payment_o2ti" style="">Selecione o banco</div></div>
                    </div>
 <?php endif; ?>
<?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
                <div id="moip_boleto" style="display:none;float: left;width:300px;margin-bottom:25px;">
<h3>Boleto Bancário</h3>
                 <span style="font-size: 10px;font-weight: bold;font-style: italic;">
                 
<?php
$standard = Mage::getSingleton('moip/standard');
$parcelamento = $standard->getInfoParcelamento();
if ($parcelamento['de2'] != 0)
{
echo "<span style=\"font-size: 14px;font-weight: bold;font-style: italic;\">Com desconto de  ".$parcelamento['de2']."%</span></br>";
}
echo "Pagável em qualquer agência bancária ou casas lotéricas.";

?>
</span>
</div>
<?php endif; ?> 
<?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
              <div id="moip_credito" style="display:none;float:left;width:210px;margin-bottom:25px;">
<div id="formcard" style="width:300px; margin-bottom:10px;">
<h3>Cartão de Crédito</h3>
    <li style="list-style:none; float:left;padding-top:10px">
<label style="float:left; width:100px;font-size:12px;padding-top:5px;">Cartão:</label>
    <select name="payment[credito_instituicao]" id="credito_instituicao" class="required-entry" autocomplete="off">
      <option value="">Selecione o Cartão</option>
      <option value="Visa">Visa</option>
      <option value="Mastercard">Mastercard</option>
      <option value="AmericanExpress">American Express</option>
      <option value="Diners">Diners</option>
      <option value="Hipercard">Hipercard</option>
    </select>
    </li>
    <li style="list-style:none; float:left;padding-top:10px">
<label style="float:left; width:100px;font-size:12px;padding-top:5px;">Número:</label>
    <input type="text" name="payment[credito_numero]" id="credito_numero" class="required-entry"  autocomplete="off" />
    </li>    
    <li style="list-style:none; float:left;padding-top:10px">
    <label style="float:left; width:100px;font-size:12px;padding-top:5px;">Expiração:</label>
    <select name="payment[credito_expiracao_mes]" id="credito_expiracao_mes" class="required-entry"  autocomplete="off">
      <option value="">Mês</option>
      <option value="01">01</option>
      <option value="02">02</option>
      <option value="03">03</option>
      <option value="04">04</option>
      <option value="05">05</option>
      <option value="06">06</option>
      <option value="07">07</option>
      <option value="08">08</option>
      <option value="09">09</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
    </select>
    <select name="payment[credito_expiracao_ano]" id="credito_expiracao_ano" class="required-entry"  autocomplete="off">
      <option value="">Ano</option>
      <option value="12">12</option>
      <option value="13">13</option>
      <option value="14">14</option>
      <option value="15">15</option>
      <option value="16">16</option>
      <option value="17">17</option>
      <option value="18">18</option>
      <option value="19">19</option>
      <option value="20">20</option>
      <option value="21">21</option>
      <option value="22">22</option>
      <option value="23">23</option>
      <option value="24">24</option>
      <option value="25">25</option>
    </select>
    </li>
    <li style="list-style:none; float:left;padding-top:10px">
<label style="float:left; width:100px; font-size:12px;">Código de <br />segurança:</label>
    <input type="text" name="payment[credito_codigo_seguranca]" class="required-entry"  style="width: 30px" id="credito_codigo_seguranca" autocomplete="off" />
    </li>
<?php if ($standad->getConfigData('parcelamento')): ?>
    <li style="list-style:none; padding-top:10px;float:left;">
<label style="float:left; width:200px;font-size:12px;padding-top:5px;">Opções de pagamento:</label>
    <select name="payment[credito_parcelamento]" id="credito_parcelamento" class="required-entry" >
                                <?php
                                    $data = $standad->getQuote()->getShippingAddress();
                                    $parcelamento = $api->getParcelamento($data->getGrandTotal());

                                    foreach ($parcelamento as $k => $v): ?>
                                        <option value="<?php echo $k ?>"><?php echo $k . "x R$ " . number_format($v['valor'], "2", ",", ".") . " | Total: R$ " . number_format($v['total'], "2", ",", "."); $v['juros'] ?></option>
                                <?php endforeach; ?>
                                    </select>
    
    <span style="font-size: 10px;float:left; width:200px;">
                                <i>
									<?php
                                    $standard = Mage::getSingleton('moip/standard');
                                            $parcelamento = $standard->getInfoParcelamento();
                                    if ($parcelamento['juros1'] == 0)
                                    {
                                    echo "</br><span style=\"font-size: 14px;font-weight: bold;font-style: italic;\">Sem juros até ".$parcelamento['ate1']." parcelas</span>";
                                    if ($parcelamento['ate1'] < 13)
                                    {
                                    echo ", após juros de 1.99 ao mês.";
                                    }
                                    }
                                    if ($parcelamento['juros1'] >= "1.99")
                                    {
                                    echo "</br>Com juros de ".$parcelamento['juros1']." ao mês.";
                                    }
                                    ?>
                                 </i>
                                 </span>
	   </li>
        <?php endif; ?>
</div>
<div id="formcli" style="width:300px; float:left; margin-top:15px;">
    <h3>Dados do Titular</h3>
   
   <li style="list-style:none; padding-top:10px;float:left">
<label style="float:left; width:100px; font-size:12px;">Nome no cartão:</label>
<input type="text" name="payment[credito_portador_nome]" class="required-entry"  id="credito_portador_nome" autocomplete="off" />
   </li>
   <li style="list-style:none; padding-top:10px;float:left">
<label style="float:left; width:100px; font-size:12px;">CPF:</label>
<input type="text" name="payment[credito_portador_cpf]" class="required-entry"  placeholder="Ex. 111.111.111-11"  id="credito_portador_cpf" value="<?php echo $cpf; ?>" autocomplete="off" />
<script type="text/javascript">
	//<![CDATA[
	// Adicionar classe de validação de cpf e cnpj ao Taxvat
	$('credito_portador_cpf').addClassName('validar_cpf');
	Validation.add('validar_cpf', 'O CPF ou CNPJ informado \xE9 invalido', function(v){return validaCPF(v,0);});
	//]]>

	</script>
   </li>
   <li style="list-style:none; padding-top:10px;float:left">
<label style="float:left; width:100px; font-size:12px;">Telefone:</label>
         <input type="text" name="payment[credito_portador_telefone]" id="credito_portador_telefone" onkeypress="return txtBoxFormat(this, '(99)9999-9999', event);" maxlength="14" placeholder="Ex. (19)9999-9999" class="required-entry"  autocomplete="off" />
   </li>
   <li style="list-style:none; padding-top:10px;float:left">
<label style="float:left; width:100px; font-size:12px;">Data nascimento:</label>
         <input type="text" name="payment[credito_portador_nascimento]" id="credito_portador_nascimento" onkeypress="return txtBoxFormat(this, '99/99/9999', event);" maxlength="10" value="<?php echo $dn ?>"  placeholder="Ex. 10/10/1985" class="required-entry"  autocomplete="off" />
   </li>
 </div> 
            <?php endif; ?>
 
</ul>
<div id="moip_o2preencha" style="display:none;float:left;width:300px;margin-bottom:25px;">Por favor, primeiro preencha o endereço de cobrança!</div>
<div id="checkout-payment-o2ti"></div>

</br></br>