<script type="text/javascript">
//busca CEP
function XMLHTTPRequest() {
  try {
    return new XMLHttpRequest(); 
  } catch(ee) {
    try {
      return new ActiveXObject("Msxml2.XMLHTTP");
    } catch(e) {
      try {
        return new ActiveXObject("Microsoft.XMLHTTP"); 
      } catch(E) {
        return false; // doesn't support
      }
    }
  }
}
function buscarEndereco(whatform) {	
if (whatform=="billing"){
	var campos = {  
	  postcode: document.getElementById('billing:postcode'),
	  street_1: document.getElementById('billing:street1'),
	  street_4: document.getElementById('billing:street4'),
	  city: document.getElementById('billing:city'),
	  region: document.getElementById('billing:region')
	};
}
if (whatform=="shipping"){
	var campos = {  
	  postcode: document.getElementById('shipping:postcode'),
	  street_1: document.getElementById('shipping:street1'),
	  street_4: document.getElementById('shipping:street4'),
	  city: document.getElementById('shipping:city'),
	  region: document.getElementById('shipping:region')
	};
}
if (whatform=="register"){
	var campos = {  
	  postcode: document.getElementById('postcode'),
	  street_1: document.getElementById('street_1'),
	  street_4: document.getElementById('street_4'),
	  city: document.getElementById('city'),
	  region: document.getElementById('region')
	};
}

<?php $urldosite = Mage::getBaseUrl('web', true);?>
var ajax = XMLHTTPRequest();
ajax.open('GET', ('<?php echo $urldosite?>buscacep.php?cep=' + campos.postcode.value.replace(/\+/g, '')), true);
  ajax.onreadystatechange = function() {
  if (ajax.readyState == 1) {
  campos.street_1.disabled = true;
  campos.street_3.disabled = true;
  campos.street_4.disabled = true;
  campos.city.disabled = true;
  campos.region.disabled = true;
  } else if (ajax.readyState == 4) {
  if(ajax.responseText == false){
    campos.street_1.disabled = false;
	campos.street_2.disabled = false;
	campos.street_3.disabled = false;
	campos.street_4.disabled = false;
    campos.city.disabled = false;
    campos.region.disabled = false;
    campos.street_1.value = "CEP inválido!";
	campos.street_4.value = "";
  }else{
    var r = ajax.responseText, i, street_1, street_4, city, region;
    street_1 = r.substring(0, (i = r.indexOf(':')));
    campos.street_1.disabled = false;
    campos.street_1.value = unescape(street_1.replace(/\+/g," "));
    r = r.substring(++i);
	street_4 = r.substring(0, (i = r.indexOf(':')));
    campos.street_4.disabled = false;
    campos.street_4.value = unescape(street_4.replace(/\+/g," "));
    r = r.substring(++i);
    city = r.substring(0, (i = r.indexOf(':')));
    campos.city.value = unescape(city.replace(/\+/g," "));
	r = r.substring(++i);
    region = r.substring(0, (i = r.indexOf(';')));
    campos.region.value = unescape(region.replace(/\+/g," "));
	campos.region.readOnly=true;
	campos.city.readOnly=true;
     };
  };
};
ajax.send(null);
};
</script>				
<?php 
$_dob = $this->getLayout()->createBlock('customer/widget_dob');
$_gender = $this->getLayout()->createBlock('customer/widget_gender');
 $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');

$name='';$company='';$email='';$street='';$city='';$state='';$zipcode='';$country='';$telephone='';$fax='';$dob='';
$gender='';$taxvat = '';
if ($_dob->isEnabled())
$dob= $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
if ($_gender->isEnabled())
$gender='<div class="field">'.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'</div>';
if ($_taxvat->isEnabled())
$taxvat = '<div class="field">'.$_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'</div>';
$name=$this->getLayout()->createBlock('customer/widget_name')->setTemplate('mw_onestepcheckout/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
if(version_compare(Mage::getVersion(),'1.4.0.1','>=')){
					$company='<div class="field">
									<label for="billing:company" class="required"><em>'.$this->isstar('company').'</em>'.$this->__('Company').'</label>
										<div class="input-box">
											<input type="text" id="billing:company" name="billing[company]" value="'.$this->htmlEscape($this->getAddress()->getCompany()).'" title="'.$this->__('Company').'" class="input-text inputtext '.$this->isrequired('company').'" />
										</div>
							</div>';
		//$email="";
		
					$email='<div class="field">
							<label for="billing:email" class="required"><em>*</em>'.$this->__('Email Address').'</label>
								<div class="input-box">
									<input type="text" name="billing[email]" id="billing:email" value="'.$this->htmlEscape( Mage::getSingleton('customer/session')->getCustomer()->getEmail()).'" title="'.$this->__('Email Address').'" '.($this->isCustomerLoggedIn() == true ? "readonly = \'true\'" : "" ).'" class="input-text inputtext validate-email required-entry" />
								</div>
							</div>';
		//}
					$street='<div>
								<ul>
										<li class="wide">
											<label for="billing:street1" class="required"><em>'.$this->isstar('street').'</em>'.$this->__('Address').'</label>
											<div class="input-box">
												<input type="text" title="'.$this->__('Street Address').'" name="billing[street][]" id="billing:street1" value="'.$this->htmlEscape($this->getAddress()->getStreet(1)).'" class="input-text inputtext  '.$this->isrequired('street').'" />
											</div>
										</li>
										<li class="wide">
											<label for="billing:street2" class="required"><em>'.$this->isstar('street').'</em>'.$this->__('Número').'</label>
											<div class="input-box">
												<input type="text" title="Street Address 2" style="width: 45px;"  name="billing[street][]" id="billing:street2" value="'.$this->htmlEscape($this->getAddress()->getStreet(2)).'" class="input-text inputtext  required-entry">
											</div>
										</li>
										<li class="wide">
											<label for="billing:street3" class="required">'.$this->__('Complemento').'</label>
											<div class="input-box">
												<input type="text" title="Complemento" style="width: 101px;"  name="billing[street][]" id="billing:street3" value="'.$this->htmlEscape($this->getAddress()->getStreet(3)).'" class="input-text inputtext">
											</div>
										</li>
										<li class="wide">
											<label for="billing:street4" class="required"><em>'.$this->isstar('street').'</em>'.$this->__('Bairro').'</label>
											<div class="input-box">
												<input type="text" title="Bairro" style="width: 101px;" name="billing[street][]" id="billing:street4" value="'.$this->htmlEscape($this->getAddress()->getStreet(4)).'" class="input-text inputtext required-entry">
											</div>
										</li>
										
										';
				
					$street=$street.'</ul></div>';
					
					$city='<div class="field">
								<label for="billing:city" class="required"><em>'.$this->isstar('city').'</em>'.$this->__('City').'</label>
								<div class="input-box">
									<input type="text" title="'.$this->__('City').'" name="billing[city]" value="'.$this->htmlEscape($this->getAddress()->getCity()).'" class="input-text inputtext  '.$this->isrequired('city').'" id="billing:city" />
								</div>
							</div>';
					
					$state=	'<div class="field">
								<label for="billing:region_id" class="required"><em>'.$this->isstar('state').'</em>'.$this->__('State/Province').'</label>
								<div class="input-box">
									<select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" '.((Mage::getStoreConfig("onestepcheckout/addfield/state")==1) ?  'class=\""validate-select\""' : " " ).'style="display:none;">
										<option value="">'.$this->__('Please select region, state or province').'</option>
									</select>
									<script type="text/javascript">
									//<![CDATA[
										$("billing:region_id").setAttribute("defaultValue",  "'.$this->getAddress()->getRegionId().'");
									//]]>
									</script>
									<input type="text" maxlength="2" id="billing:region" name="billing[region]" value="'.$this->htmlEscape($this->getAddress()->getRegion()).'"  title="'.$this->__('State/Province').'" class="input-text inputtext  '.$this->isrequired('state').'" style="display:none;" />
								</div>
							</div>';
					
					$zipcode='<div class="field">
									<label for="billing:postcode" class="required"><em>'.$this->isstar('zip').'</em>'.$this->__('Zip/Postal Code').'</label>
									<div class="input-box">
										<input type="text" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" id="billing:postcode" value="'.$this->htmlEscape($this->getAddress()->getPostcode()).'" class="input-text inputtext validate-zip-international  '.$this->isrequired('zip').' o2tizip" placeholder="99999-999" onchange="javascript: buscarEndereco(\'billing\');"  onkeypress="return txtBoxFormat(this, \'99999-999\', event);" maxlength="9" />
									</div>
								</div>
								<div class="field">
									<div class="input-box" style="margin-top:20px">
									<a id="correio" href="#inlinecorreio" title="">Pesquise seu CEP?</a>
									</div>
								</div>';
					
					$country='<div class="field" '.((Mage::getStoreConfig("onestepcheckout/addfield/country")==0 ) ? "style=\"display:none\"" : "").'>
									<label for="billing:country_id" class="required"><em>'.$this->isstar('country').'</em>'.$this->__('Country').'</label>
									<div class="input-box">
										'.$this->getCountryHtmlSelect('billing').'
									</div>
								</div>	'	;
							
					$telephone=	'<div class="field">
									<label for="billing:telephone" class="required"><em>'.$this->isstar('telephone').'</em>'.$this->__('Telephone').'</label>
									<div class="input-box">
										<input type="text" name="billing[telephone]" value="'.$this->htmlEscape($this->getAddress()->getTelephone()).'" title="'.$this->__('Telephone').'" class="input-text inputtext  '.$this->isrequired('telephone').'" id="billing:telephone" placeholder="(99)9999-9999"  onkeypress="return txtBoxFormat(this, \'(99)9999-9999\', event);" maxlength="14" />
									</div>
								</div>';
					$fax=	'<div class="field">
									<label for="billing:fax" class="required"><em>'.$this->isstar('fax').'</em>'.$this->__('Fax').'</label>
									<div class="input-box">
										<input type="text" name="billing[fax]" value="'.$this->htmlEscape($this->getAddress()->getFax()).'" title="'.$this->__('Fax').'" class="input-text inputtext  '.$this->isrequired('fax').'" id="billing:fax" placeholder="(99)9999-9999"  onkeypress="return txtBoxFormat(this, \'(99)9999-9999\', event);" maxlength="14" />
									</div>
							</div>';
}

else{	//for magento 1.3x
					$company='<div class="input-box"><label for="billing:company">'.$this->__('Company').'<span class="required">'.$this->isstar('company').'</span></label><br /><input type="text" id="billing:company" name="billing[company]" value="'.$this->htmlEscape($this->getAddress()->getCompany()).'" title="'.$this->__('Company').'" class="input-text  '.$this->isrequired('company').'" /></div>';
					//$email="";
					//if(!$this->isCustomerLoggedIn()){
						$email='<div class="input-box"><label for="billing:email">'.$this->__('Email Address').'<span class="required">*</span></label><br /><input type="text" name="billing[email]" id="billing:email"  '.($this->isCustomerLoggedIn() == true ? "readonly = \'true\'" : "" ).'"  value="'.$this->htmlEscape( Mage::getSingleton('customer/session')->getCustomer()->getEmail()).'" title="'.$this->__('Email Address').'" class="validate-email input-text  required-entry" /></div>';
					//}
					$street='<div><ul><li><label for="billing:street1">'.$this->__('Address').'<span class="required">'.$this->isstar('street').'</span></label><br /><input type="text" title="'.$this->__('Street Address').'" name="billing[street][]" id="billing:street1" value="'.$this->htmlEscape($this->getAddress()->getStreet(1)).'" class="input-text  '.$this->isrequired('street').'" /></li>';
					for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){
						$street=$street.'<li><input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($this->getAddress()->getStreet($_i)).'" class="input-text" /></li>';
					}
					$street=$street.'</ul></div>';
					$city='<div class="input-box"><label for="billing:city">'.$this->__('City').'<em>'.$this->isstar('city').'</em></label><br /><input type="text" title="'.$this->__('City').'" name="billing[city]" value="'.$this->htmlEscape($this->getAddress()->getCity()).'" class="input-text  '.$this->isrequired('city').'" id="billing:city " /></div>';
					$state='<div class="input-box"><label for="billing:region">'.$this->__('State/Province').'<span class="required">*</span><em>'.$this->isstar('state').'</em></label><br/><select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" '.((Mage::getStoreConfig("onestepcheckout/addfield/state")==1) ?  'class=\""validate-select\""' : "" ).' style="display:none"><option value="">'.$this->__('Please select region, state or province').'</option></select><script type="text/javascript">$("billing:region_id").setAttribute("defaultValue",  "'.$this->getAddress()->getRegionId().'");</script><input type="text" id="billing:region" name="billing[region]" value="'.$this->htmlEscape($this->getAddress()->getRegion()).'"  title="'.$this->__('State/Province').'" class="input-text  '.$this->isrequired('state').'" style="display:none" /></div>';
					$zipcode='<div class="input-box"><label for="billing:postcode">'.$this->__('Zip/Postal Code').'<span class="required">'.$this->isstar('zip').'</span></label><br /><input type="text" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" id="billing:postcode" value="'.$this->htmlEscape($this->getAddress()->getPostcode()).'" class="validate-zip-international input-text  '.$this->isrequired('zip').'" /></div>';
					$country='<div class="input-box" '.((Mage::getStoreConfig("onestepcheckout/addfield/country")==0) ? "style=\"display:none\"" : "").'><label for="billing:country_id">'.$this->__('Country').'<span class="required">*</span></label><br />'.$this->getCountryHtmlSelect('billing').'</div>';
					$telephone='<div class="input-box"><label for="billing:telephone">'.$this->__('Telephone').'<span class="required">'.$this->isstar('telephone').'</span></label><br/><input type="text" name="billing[telephone]" value="'.$this->htmlEscape($this->getAddress()->getTelephone()).'" title="'.$this->__('Telephone').'" class="input-text  '.$this->isrequired('telephone').'" id="billing:telephone" /></div>';
					$fax='<div class="input-box"><label for="billing:fax">'.$this->__('Fax').'<span class="required">'.$this->isstar('fax').'</span></label><br/><input type="text" name="billing[fax]" value="'.$this->htmlEscape($this->getAddress()->getFax()).'" title="'.$this->__('Fax').'" class="input-text  '.$this->isrequired('fax').'" id="billing:fax" /></div>';
}


$type_address=array('company','email','street','city','state','zip','country','telephone','fax','dob','gender','taxvat');
//$type_address=array('name','company','email','street','city','state','zip','country','telephone','fax');

$block=array("","","","","","","","","","","","");

//var_dump($block);die();
$temp=array();
$notdisable=array();
$filter=array();
foreach($type_address as $nametype){
	if($nametype=='email')
	$notdisable[] = 'email';
	else 
	{
	if(!$this->isdisable($nametype))
		$notdisable[]=$nametype;
	}
}
foreach($notdisable as $namevalid){
	$filter[]=Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$namevalid);
	//$filter=array(Mage::getStoreConfig('onestepcheckout/options_sort/sort_name'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_company'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_email'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_street'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_city'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_state'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_zip'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_country'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_telephone'),Mage::getStoreConfig('onestepcheckout/options_sort/sort_fax'));
}
for($i=0;$i<count($filter);$i++){
	for($j=$i+1;$j<count($filter);$j++){
		if($filter[$i]==$filter[$j]){
			$temp[]=$filter[$i];
			break;
		}
	}
}
$temp[]=Mage::getStoreConfig('onestepcheckout/options_sort/sort_name');
//$temp[]=Mage::getStoreConfig('onestepcheckout/options_sort/sort_street');
//var_dump($temp);die();
$nameinputs=array(		
		'company'=>$company,
		'email'=>$email,
		'street'=>$street,
		'city'=>$city,
		'state'=>$state,
		'zip'=>$zipcode,
		'country'=>$country,
		'telephone'=>$telephone,
		'fax'=>$fax,
		'dob'=>$dob,
		'gender'=>$gender,
		'taxvat'=>$taxvat
);
	foreach($nameinputs as $nameadd =>$blockitem){
		
			if(!in_array($nameadd,$notdisable)){	//neu input da bi disable trong configuration
				continue;
			}
			if(!in_array(Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd),$temp)){
				if($nameadd=='dob')
				{
					$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)]=$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)].$blockitem;
				}
				else 
				{
					$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)]='<div class="widthfull">'.$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)].$blockitem.'</div>';
				}
			}
			else{					
					$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)]=$block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_'.$nameadd)].$blockitem;
			}
				
	}
$str = '<script type="text/javascript" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'mw_onestepcheckout/billing.js'.'"></script>';
$str =$str.'<li class="fields">'.$name.'</li>';
//var_dump($street);die();
foreach($block as $blockitem){
	if($blockitem ==""){
		continue;
	}
	if(version_compare(Mage::getVersion(),'1.4.0.1','>=')){
		if($blockitem == 'dob')
		{
			$str = $str.'<li class="fields"><div class="field">'.$blockitem.'</div></li>';
		}
		else
			$str = $str.'<li class="fields">'.$blockitem.'</li>';
	}
	else{
		$str=$str.'<li>'.$blockitem.'</li>';
	}
}
//add country but hidden when disable contry
if(!Mage::getStoreConfig("onestepcheckout/addfield/country") )
$str =$str.'<li class="fields">'.$country.'</li>';

if($this->isdisable($nametype))
	$str=$str.'<div style="display:none;"><select id="billing:region_id" name="billing[region_id]" ></select></div>';
$str =$str.'<script type="text/javascript">
	$MW_Onestepcheckout(function(){		
				$MW_Onestepcheckout("#billing-new-address-form").show(); 
		});	
//<![CDATA[
	var billing = new Billing("co-billing-form","'.$this->getUrl('checkout/onepage/getAddress').'address/", "'.$this->getUrl('checkout/onepage/saveBilling').'");
 	var billingForm = new VarienForm("co-billing-form");   
    var billingRegionUpdater = new RegionUpdater("billing:country_id", "billing:region", "billing:region_id", countryRegions, undefined, "billing:postcode");
//]]>

</script>';
echo $str;
?>
