<?php 

$_order = Mage::registry('current_order');
$orderid=$_order->getId();
$orders=Mage::getModel('onestepcheckout/onestepcheckout')->getCollection()->addFieldToFilter('sales_order_id',$orderid);
$class_orders=get_class($orders);	//cha ve name class cua doi tuong
$o ='';

foreach($orders as $order)	//$orders chua nhieu doi tuong. va` chi lay dc doi tuong con qua foreach
{
	$o = $order; break;		//vi` record nam o doi tuong dau tien, nen chi can lay doi tuong dau tien
}
?>
<?php
//echo $orderid;die();
//echo '<pre>';var_dump($_order->getCollection()->getData());die();
 ?>
<div class="clear"></div>
<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-shipping-method"><?php echo $this->helper('onestepcheckout')->__('Customer Order Comment') ?></h4>
		</div>
		<fieldset>
		<?php if($o):?>
			<?php echo $o->getMwCustomercommentInfo();//$order->getMwCustomercommentInfo() ;//$_order->getMwCustomercomment() ?>
		<?php endif?>
		</fieldset>
	</div>
</div>
<?php
