<?php if(Mage::getStoreConfig('onestepcheckout/config/enabled')):?>

<script type="text/javascript">
var message_payment = "<?php echo Mage::helper('onestepcheckout')->__('Please select a payment method for your order!');?>";
var message_ship = "<?php echo Mage::helper('onestepcheckout')->__('Please select a shipping method for your order!');?>";

//update review order when change shipping method
function updateShippingMethod()	
{
	urls= '<?php echo Mage::getUrl('onestepcheckout/index/updateshippingmethod') ?>';

	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: urls,
	   data: "shipping_method="+$MW_Onestepcheckout('input[name=shipping_method]:checked').val(),
	    success: function(msg){
		 msg=msg.replace("[]","");
		$MW_Onestepcheckout('#checkout-review-load').html(msg);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});
}

//update review order when change payment method
function updatePaymentMethod(value)	
{
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymentmethod')?>",
	   data: "payment%5Bmethod%5D="+value,
	   success: function(msg){
		if(msg.search("<script")!=0){		
		$MW_Onestepcheckout('#checkout-review-load').html(msg);
		}
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	 });
}

//update review order and tab coupon when enter coupon code
function updateCoupon(code,isremove){		
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatecoupon')?>",
	   data: "coupon_code="+code+"&remove="+isremove,
	   success: function(msg){
		str=jQuery.parseJSON(msg);
		//console.debug(str.coupon);
		//console.debug(str.view);
		$MW_Onestepcheckout('#tab-coupon').html(str.coupon);
		$MW_Onestepcheckout('#checkout-review-load').html(str.view);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});	
}

//update review order when update product
function updateQtyProduct(){	
	qtydata=$MW_Onestepcheckout("input[name^='cart\[']"); //selector all element have name ~ cart[
	//console.debug(qtydata.length);
	str='';
	for(var i=0;i< qtydata.length;i++){
		//console.debug(qtydata[i]);
		str_escape=escape(qtydata[i].name)+"="+qtydata[i].value;
		str+=str_escape;
		if(i!=qtydata.length-1){str+="&"}
	}
	//str_escape=escape(str);
	//console.debug(str_escape);
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updateqty')?>",
	   data: str,
	   success: function(msg){
		str=jQuery.parseJSON(msg);

		if(str.view.search("<script")!=0){
		//alert(msg.search("<script"));
		$MW_Onestepcheckout('#checkout-review-load').html(str.view);
		}
		else
			$MW_Onestepcheckout('#checkout-review-load').append(str.view);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});		
}
function removeProduct(id){		//update review order khi remove product
	//kiem tra xem co block gift message
	hasgift=(typeof($MW_Onestepcheckout('#allow-gift-message-container'))!='undefined')?1:0;
	//alert(typeof($MW_Onestepcheckout('#allow-gift-message-container')));
	//console.debug($hasgift);
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
		type: "POST",
		url: "<?php echo Mage::getUrl('onestepcheckout/index/removeproduct')?>",
		data: "id="+id+'&hasgiftbox='+hasgift,
		success: function(msg){
		str=jQuery.parseJSON(msg);

		if(str.view.search("<script")!=0){
			if(str.giftbox){
				$MW_Onestepcheckout('#checkout-review-load').html(str.view);
				$MW_Onestepcheckout('#onepage-checkout-shipping-method-additional-load').html(str.giftbox);
			}else{
				$MW_Onestepcheckout('#checkout-review-load').html(str.view);
			}
		}
		else{
			$MW_Onestepcheckout('#checkout-review-load').append(str.view);			
		}
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});	
}

// when onepagecheckout has two columns
function reDrawOnepage()
{
	$MW_Onestepcheckout(".mw-osc-column-left").css({'width':'32%'});
	$MW_Onestepcheckout(".mw-osc-column-2").css('width','66%');
	$MW_Onestepcheckout(".mw-osc-column-right").css({'float':'none','clear':'both'});
	$MW_Onestepcheckout(".mw-osc-column-middle").css('width','100%');	 
	$MW_Onestepcheckout(".mw-osc-column-right").css('width','100%');	 	
}

// onload event
$MW_Onestepcheckout(function(){
	 //load css when show date of birth
	$MW_Onestepcheckout(".customer-dob").css('width','300px');
	$MW_Onestepcheckout(".cart .discount").css({'border':'none','background':'none'});
	
	<?php
	$color ="#337BAA";
	if(Mage::getStoreConfig('onestepcheckout/config/style_color')!= "")
	 $color = "#".Mage::getStoreConfig('onestepcheckout/config/style_color');
	 ?>
	 
	 //$MW_Onestepcheckout(".mw-osc-block-title").css('backgroundColor','<?php echo $color;?>');
	
	 <?php
	 if(Mage::getStoreConfig('onestepcheckout/config/page_layout')==2):?> 
	 reDrawOnepage();
	 <?php endif?>
	 
	<?php if(Mage::getStoreConfig('onestepcheckout/config/is_sort_add')):?>
		<?php  if(Mage::getStoreConfig('onestepcheckout/addfield/zip') !=2):?>	//  remove required-entry field postcode when config field postcode is not required ,
			$MW_Onestepcheckout('#billing\\:postcode').removeClass('required-entry');	
			$MW_Onestepcheckout('#shipping\\:postcode').removeClass('required-entry');
		<?php endif?>
		<?php  if(Mage::getStoreConfig('onestepcheckout/addfield/state') !=2):?>  // field region state
			$MW_Onestepcheckout('#billing\\:region_id').removeClass('validate-select');
			$MW_Onestepcheckout('#shipping\\:region_id').removeClass('validate-select');
		<?php endif?>		
	<?php endif?>

	//neu có config default shipping method khi checkout thi checked cho input shipping method
	<?php if(Mage::getStoreConfig("onestepcheckout/config/default_shippingmethod")):?>	
		var defaultshippingmethod = "<?php echo Mage::getStoreConfig("onestepcheckout/config/default_shippingmethod")?>";
		var defaultshippingmethodId = "#s_method_"+defaultshippingmethod;
			$MW_Onestepcheckout(defaultshippingmethodId).attr('checked','checked');	//fix truong hop lan dau tien vao checkout thi shipping method khong dc check
	<?php endif?>	

	//xoa du lieu tren form billing address neu' co du lieu san~ tren cac field input
		// truong hop chua login
		if(logined() )
		{
			if(!has_default_billing())	
			{		
				$MW_Onestepcheckout('#billing-new-address-form').clearForm();
				$MW_Onestepcheckout('#shipping-new-address-form').clearForm();
			}
		}
		else
		{
			$MW_Onestepcheckout('#billing-new-address-form').clearForm();
			$MW_Onestepcheckout('#shipping-new-address-form').clearForm();
		}
		
			
	// function clearForm() -> js.js line 288
	
	//add fancy box cho form click login, click forgot password
		$MW_Onestepcheckout("#loginbox").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none',
			'width'				:	'400',
			'height	'			:	'250'
		});
		$MW_Onestepcheckout("#onestepcheckout-toc-link").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});
		$MW_Onestepcheckout("#forgotpassword").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});
		$MW_Onestepcheckout("#backlogin").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});	

	<?php	
	// neu customer dang login ($islogin)va co thong tin cho address ($had_address)
		$islogin=0;
		if(Mage::getSingleton('customer/session')->isLoggedIn()){
			$islogin=1;	//dang login
		}
	?>		

	//neu shipping method co ton tai 1 phuong thuc' duoc checked thi update view	
	var completeajax=1;	
	if($MW_Onestepcheckout('input[name=shipping_method]:checked').val() && shipping_load()){	
		$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
		$MW_Onestepcheckout.ajax({
		   type: "POST",
		   url:"<?php echo Mage::getUrl('onestepcheckout/index/updateshippingmethod') ?>",
		   data: "shipping_method="+$MW_Onestepcheckout('input[name=shipping_method]:checked').val(),
		   success: function(msg){
			   msg=msg.replace("[]","");
			$MW_Onestepcheckout('#checkout-review-load').html(msg);
			//$MW_Onestepcheckout('#loading-mask').css('display','none');
			
		   }
		});
	}

	//neu payment method co ton tai 1 phuong thuc' duoc checked va config cho phep payment load thi update reiew
	if($MW_Onestepcheckout('input[name=payment\\[method\\]]:checked').val() && payment_load()){ 		
		$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
		value=$MW_Onestepcheckout('input[name=payment\\[method\\]]:checked').val();		
		$MW_Onestepcheckout.ajax({
		   type: "POST",
		   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymentmethod')?>",
		   data: "payment%5Bmethod%5D="+value,
		   success: function(msg){
			if(msg.search("<script")!=0){			
			$MW_Onestepcheckout('#checkout-review-load').html(msg);
			}
			else
				$MW_Onestepcheckout('#checkout-review-load').append(msg);			
		   }
		 });
	}
	
	$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
		//valid form khi click nut PLACE ORDER
		$MW_Onestepcheckout('.btn-checkout').live("click",function(e){
				//	First validate the form
					//$MW_Onestepcheckout('#onestep_form').submit();
					//return true;
					var form = new VarienForm('onestep_form');
					var logic=true;
					<?php if(Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
							var notshipmethod=1;
					<?php else:?>
							var notshipmethod=$MW_Onestepcheckout("input[name=shipping_method]:checked").val();
					<?php endif?>
					// check for shipping type
					if(!$MW_Onestepcheckout('input[name=payment\\[method\\]]:checked').val() || !notshipmethod){
					logic=false;
					}
					// 
					if(!$MW_Onestepcheckout('input[name=payment\\[method\\]]:checked').val()){	//neu cac method payment chua duoc chon
						if(!$MW_Onestepcheckout('#advice-required-entry_payment').length){	//neu' phan tu valid chua duoc hien len, thi` cho no hien len
						$MW_Onestepcheckout('#checkout-payment-method-load').append('<dt><div class="validation-advice" id="advice-required-entry_payment" style="">'+message_payment+'</div></dt>');
						//if($MW_Onestepcheckout('#advice-required-entry_payment').attr('display')!="none"){
						//$MW_Onestepcheckout('#advice-required-entry_payment').css('display','block');
						}
					}
					else
					$MW_Onestepcheckout('#advice-required-entry_payment').remove();
					//$MW_Onestepcheckout('#advice-required-entry_payment').css('display','none');
					
					if(!notshipmethod){
						if(!$MW_Onestepcheckout('#advice-required-entry_shipping').length){
						$MW_Onestepcheckout('#checkout-shipping-method-loadding').append('<dt><div class="validation-advice" id="advice-required-entry_shipping" style="">'+message_ship+'</div></dt>');
						//if($MW_Onestepcheckout('#advice-required-entry_shipping').attr('display')!="none"){
						//$MW_Onestepcheckout('#advice-required-entry_shipping').css('display','block');
						}

					}
					else
					$MW_Onestepcheckout('#advice-required-entry_shipping').remove();
					//$MW_Onestepcheckout('#advice-required-entry_shipping').css('display','none');

					if(!form.validator.validate())	{
						if(logined()!=1){
						val=$MW_Onestepcheckout('#billing\\:email').val();
						emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
						//alert(emailvalidated);		//validate chi cho moi field email
						if(val!="" && emailvalidated){
							updateEmailmsg(val);
						}
						}
						//alert(val1);
						//val_emailbill_before=val;
						Event.stop(e);				
					}
					else{
						if(logined()!=1){
							//$MW_Onestepcheckout('#billing\\:email').blur(function(event){
							//val=this.value;
							var msgerror=1;
							val=$MW_Onestepcheckout('#billing\\:email').val();
							emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
							//alert(emailvalidated);		//validate chi cho moi field email
							if(val!="" && emailvalidated){
								msgerror=updateEmailmsg(val);
							}
							//val_emailbill_before=val;
							if(msgerror==0){
								//alert(msgerror);
								return false;
							}
						}
						
						if(logic){
						$MW_Onestepcheckout('#onestep_form').submit();
						$MW_Onestepcheckout('#loading-mask').css('display','block');
						$MW_Onestepcheckout('.btn-checkout').attr("disabled","disabled");
						}
						else {
							return false;
						}
					}
					return false;
		}
		);
});
</script>

<?php
if(Mage::getStoreConfig('onestepcheckout/config/style_color')!= ""):
	$color = "#".Mage::getStoreConfig('onestepcheckout/config/style_color');
?>
	<style type="text/css">
	.form-list .customer-dob .dob-day, .form-list .customer-dob .dob-month, .form-list .customer-dob .dob-year
		{
			 float: left;
             margin-right: 0px;
            padding-right: 0 !important;
			
		}
	.dob-year .input-text, .dob-day .input-text, .dob-month .input-text
	{
		width:80px!important;
	}
	div.mw-osc-block-title{background: <?php echo $color;?>;}
	.mw-osc-threecolumns button.button span{background:<?php echo $color;?>; border: 1px solid <?php echo $color;?>;}
	.cart .discount h2{color: <?php echo $color;?>;}
	.mw-osc-title-login{background: <?php echo $color;?>;}
	div#fancybox-wrap .col2-set .col-2 #login-form fieldset .col-2 .buttons-set button span,
	div#fancybox-wrap #form-validate div.buttons-set #btforgotpass span{background:<?php echo $color;?>; border: 1px solid <?php echo $color;?>;}
	.mw-osc-fancybox-wrap button.button span{background:<?php echo $color;?>; border: 1px solid <?php echo $color;?>;}
	.mw-osc-giftmessagecontainer .gift-messages h3{background-color: <?php echo $color;?>;}
	.mw-osc-giftmessagecontainer .gift-messages-form h4{color: <?php echo $color;?>;}
	</style>
<?php endif;?>
<div class="mw-osc">
	<hidden value="Welcome to One Step Checkout Pro"></hidden>
	<hidden value="Please enter your details below to complete your purchase."></hidden>
	<h1 class="mw-osc-page-tittle"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_title'))?></h1>
	<p class="mw-osc-page-content"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_content'))?></p>
	<div id="message-box">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() //cho phep' dua ra cac thong bao' khi ton tai addError?>	
	</div>
	<?php if(!$islogin):?>
		<?php if(Mage::getStoreConfig('onestepcheckout/config/enable_quicklogin')):?>
		<a id="loginbox" href="#inline1" title=""><?php echo $this->__('Already registered? Click here to login.');?></a>
		<?php endif?>
	<?php endif?>

	<div class="mw-osc-threecolumns mw-osc-checkoutcontainer mw-osc-skin-generic">
		<form id="onestep_form" action="<?php echo $this->getUrl('onestepcheckout/index/updateordermethod') ?>" method="POST">

			<div class="mw-osc-column mw-osc-column-left">	
				<div class="mw-osc-block">
					<div class="mw-osc-block-title">
						<p class="onestepcheckout-numbers onestepcheckout-numbers-1">
							<?php echo $this->__('Billing address');?>
						</p>
					</div>
					<div class="mw-osc-block-content">
						<div>
							<?php echo $this->getChildHtml('billing');?>
						</div>							
					</div>
					
					<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
					<?php if(Mage::getStoreConfig('onestepcheckout/config/allowshippingotheraddress')):?> 
					<div style="display:none;" id="shipping_show">
						<div class="mw-osc-block-title">
							<p class="onestepcheckout-numbers onestepcheckout-numbers-2" >
								<?php echo $this->__('Shipping address');?>
							</p>
						</div>
						<div class="mw-osc-block-content">
							<div>
								<?php echo $this->getChildHtml('shipping');?>
							</div>							
						</div>
					</div>
					<?php endif;?>
					<?php endif;?>
					
				</div>
			</div>
			
			
			<div class="mw-osc-column-2">
				<div id="mw-osc-column-container">
				<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
					<div class="mw-osc-column mw-osc-column-middle">	
						<div class="mw-osc-block">
							<div class="mw-osc-block-title">
								<p class="onestepcheckout-numbers onestepcheckout-numbers-2" id="mw-osc-p2">
									<?php echo $this->__('Shipping method');?>
								</p>
							</div>
							<?php echo $this->getChildHtml('shipping_method');?>
						</div>
					</div>
				<?php endif?>
						
					<div class="mw-osc-column  mw-osc-column-right" >
						<div class="mw-osc-block">
							<div class="mw-osc-block-title">
								<p <?php if(Mage::helper('onestepcheckout')->onlyProductDownloadable())
								          echo "class='onestepcheckout-numbers onestepcheckout-numbers-2' id='mw-osc-p2'";								          
								          else 
								          {
								          if(Mage::getStoreConfig("onestepcheckout/deliverydate/allow_options"))
								          echo "class='onestepcheckout-numbers onestepcheckout-numbers-4' id='mw-osc-p4'";
								          else echo "class='onestepcheckout-numbers onestepcheckout-numbers-3' id='mw-osc-p3'";
								          }?>>
										  <?php echo $this->__('Payment method');?>
								</p>
							</div>
							<div class="mw-osc-block-content">
								<?php echo $this->getChildHtml('payment');?>
							</div>
						</div>
					</div>
					<div class="clear_both">&nbsp;</div>
				</div>
				<div class="review">
					<div class="mw-osc-block">
						<div class="mw-osc-block-title">
							<p class="onestepcheckout-numbers onestepcheckout-numbers-6">
								<?php echo $this->__('Review your order');?>
							</p>
						</div>
						<?php echo $this->getChildHtml('review');?>
					</div>
				</div>
			</div>
			<div class="clear_both">&nbsp;</div>			
		</form>
		<?php if(version_compare(Mage::getVersion(),'1.4.0.1','>='))://fix cho magento 1.3?>
				<div style="display: none;">
					<div id="inline1" style="width:400px;height:250px;overflow:auto;">
						<?php echo $this->getChildHtml('login');?>	
					</div>
					<div id="inline3" style="width:440px;height:210px;overflow:auto;">
						<?php echo $this->getChildHtml('forgotpassword');?>	
					</div>
					<div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
						<div class="mw-osc-title-login">
							<h1><?php echo $this->__('Terms and Conditions');?> </h1>
						</div>
						<div class="mw-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')-90).'px';?>">
							<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
						</div>
					</div>
				</div>	
		<?php else:?>
				<div style="display: none;">
					<div id="inline1">
						<?php echo $this->getChildHtml('login');?>	
					</div>
					<div id="inline3" style="width:445px;height:205px;overflow:auto;">
						<?php echo $this->getChildHtml('forgotpassword');?>	
					</div>
					<div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
						<h1><?php echo $this->__('Terms and Conditions');?> </h1>
						<br>
						<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
					</div>
				</div>	
		<?php endif;?>
		</div>
	<div class="clear_both">&nbsp;</div>
</div>
<div style="left: 0px; min-height: 710px; display: none; top:0px;" id="loading-mask">
    <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('mw_onestepcheckout/images/ajax-loader-tr.gif')?>"><br>Updating information, please wait...</p>
</div>

<?php endif?>